<a href="https://colab.research.google.com/github/ShubhamKNIT/learn-python/blob/main/notebooks/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What we're going to learn:
1. Intro to tensors
2. Getting info from tensors
3. Manipulating tensors
4. Tensors & numpy
5. Using @tf.function (a way to speed up your regular Python functions)
6. Excersies to try for yourself

# Intro to Tensors

In [ ]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
 scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([1, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix with dtype
matrix_1 = tf.constant([[1., 2.],
                        [3., 4.]], dtype = tf.float32)
matrix_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
matrix_1.ndim, matrix_1.dtype

(2, tf.float32)

In [ ]:
tensor_3d = tf.constant([[[1, 2, 9],
                          [2, 3, 8]],
                         [[3, 4, 7],
                          [4, 5, 6]]])
tensor_3d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 9],
        [2, 3, 8]],

       [[3, 4, 7],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor_3d.ndim

3

### Creating tensors with `tf.Variable`
- variables are mutable, constant are
- https://stackoverflow.com/questions/44880564/tf-variable-vs-tf-constant-in-tensorflow

In [ ]:
var = tf.Variable([10, 7])
const = tf.constant([10, 7])
var, const

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try to manipulate the defined tensor variables
var[0].assign(7)
var[0]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
const[0].assign(70)
const[0]

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

In [ ]:
rand_1 = tf.random.Generator.from_seed(42)
rand_1 = rand_1.normal(shape=(2, 4))
rand_2 = tf.random.Generator.from_seed(42)
rand_2 = rand_2.normal(shape=[2, 4])

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

### Shuffle the order of elements in the tensors

- Shuffling the data might be valuable when learning is not affected (generally)

In [ ]:
rand_3 = tf.random.Generator.from_seed(7)
rand_3 = rand_3.normal(shape = (3, 4))
rand_3

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707, -0.06378496,  0.92800784],
       [-0.6039789 , -0.1766927 ,  0.04221033,  0.29037967]],
      dtype=float32)>

In [ ]:
rand_3 = tf.random.shuffle(rand_3, seed = 42)
rand_3

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.6039789 , -0.1766927 ,  0.04221033,  0.29037967],
       [ 0.69211644,  0.84215707, -0.06378496,  0.92800784],
       [-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018]],
      dtype=float32)>

### Other ways of creating tensors

In [ ]:
ones = tf.ones([3, 4])
ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
zeros = tf.zeros([3, 4])
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turning numpy into tensors

- Numpy array can be run on CPU/GPU, whereas Tensors can run on both including TPU.

In [ ]:
import numpy as np
arr_1 = np.arange(1, 11, dtype = np.int32)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [ ]:
arr_1 = np.reshape(arr_1, newshape = [2, 5])
arr_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)

In [ ]:
tf_arr_1 = tf.constant(arr_1)
tf_arr_1

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [ ]:
tf_arr_2 = tf.constant(arr_1, shape = [1, 10])
tf_arr_2

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

In [ ]:
tf_arr_3 = tf.reshape(tf_arr_2, shape = [5, 2])
tf_arr_3

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)>

# Getting information from tensors
- shape
- rank
- axis or dimensions
- size

In [ ]:
rank4_tf = tf.zeros([2, 3, 5, 5])
rank4_tf

<tf.Tensor: shape=(2, 3, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], d

In [ ]:
rank4_tf.shape, rank4_tf.ndim, rank4_tf.dtype, tf.size(rank4_tf), tf.size(rank4_tf).numpy()

(TensorShape([2, 3, 5, 5]),
 4,
 tf.float32,
 <tf.Tensor: shape=(), dtype=int32, numpy=150>,
 150)

### Indexing tensors

In [ ]:
rank4_tf[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
arr_2 = np.arange(1, 97, dtype = np.int32)
rank4_tf2 = tf.constant(arr_2, shape = [2, 3, 4, 4])
rank4_tf2

<tf.Tensor: shape=(2, 3, 4, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]],


       [[[49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60],
         [61, 62, 63, 64]],

        [[65, 66, 67, 68],
         [69, 70, 71, 72],
         [73, 74, 75, 76],
         [77, 78, 79, 80]],

        [[81, 82, 83, 84],
         [85, 86, 87, 88],
         [89, 90, 91, 92],
         [93, 94, 95, 96]]]], dtype=int32)>

In [ ]:
rank4_tf2[:, :, 0, 0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 17, 33],
       [49, 65, 81]], dtype=int32)>

In [ ]:
rank4_tf2[:, :, -1, -1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[16, 32, 48],
       [64, 80, 96]], dtype=int32)>

In [ ]:
rank3_tf = tf.zeros(shape = [3, 3])
rank3_tf

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
# adding extra axis to tensors
rank3_tf[tf.newaxis, :,:]

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
# alternate way to add extra axis to tensors
tf.expand_dims(rank3_tf, 2)

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

In [ ]:
# dimension expand beyond the original ndim range (-ndim, ndim)
tf.expand_dims(rank4_tf2, 2)

<tf.Tensor: shape=(2, 3, 1, 4, 4), dtype=int32, numpy=
array([[[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]]],


        [[[17, 18, 19, 20],
          [21, 22, 23, 24],
          [25, 26, 27, 28],
          [29, 30, 31, 32]]],


        [[[33, 34, 35, 36],
          [37, 38, 39, 40],
          [41, 42, 43, 44],
          [45, 46, 47, 48]]]],



       [[[[49, 50, 51, 52],
          [53, 54, 55, 56],
          [57, 58, 59, 60],
          [61, 62, 63, 64]]],


        [[[65, 66, 67, 68],
          [69, 70, 71, 72],
          [73, 74, 75, 76],
          [77, 78, 79, 80]]],


        [[[81, 82, 83, 84],
          [85, 86, 87, 88],
          [89, 90, 91, 92],
          [93, 94, 95, 96]]]]], dtype=int32)>

# Manipulating Tensors

- Basic Operations: `+`, `-`, `*`, `\`, `%`, `//`
- using tf.math.func() or tf.func() e.g, tf.add(a, b) operates the data on TPU, then the simple operations like a + b

In [ ]:
const_1 = tf.constant([[1, 2, 3],
                       [4, 5, 6]], dtype = tf.int32)
const_1 + 4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)>

In [ ]:
const_1 - 4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-3, -2, -1],
       [ 0,  1,  2]], dtype=int32)>

In [ ]:
const_1 * 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
const_1 / 2

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])>

In [ ]:
const_1 // 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 1],
       [2, 2, 3]], dtype=int32)>

In [ ]:
const_1 % 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)>

In [ ]:
tf.add(const_1, 2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.subtract(const_1, const_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
tf.multiply(const_1, [[2],[3]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [12, 15, 18]], dtype=int32)>

In [ ]:
tf.tensordot(const_1, [1, 2,3], axes = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([14, 32], dtype=int32)>

In [ ]:
const_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.tensordot(const_1, [[1],[2]], axes = 0)

<tf.Tensor: shape=(2, 3, 2, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2]],

        [[ 2],
         [ 4]],

        [[ 3],
         [ 6]]],


       [[[ 4],
         [ 8]],

        [[ 5],
         [10]],

        [[ 6],
         [12]]]], dtype=int32)>

### Matrix Multiplication in tensorflow
$$A_{(m,n1)} x B_{(n2,n)} = C_{(m, n)}; n1 == n2 $$



In [ ]:
# Matrix mulitplication A x B with python
const_1@tf.transpose(const_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [ ]:
# Matrix multiplication with tensor
tf.matmul(const_1, tf.transpose(const_1))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

### Dot Product
- Matrix multiplication is also referred to as dot product
- `tf.tensordot()`
- `tf.matmul()`


In [ ]:
# Dot product using tensordot()
tf.tensordot(const_1, tf.transpose(const_1), axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [ ]:
tf.matmul(const_1, tf.transpose(const_1))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

### Changing DataType of tensor
- Mixed Precision: https://www.tensorflow.org/guide/mixed_precision
- APIs: https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision

- Converting numbesrs to lower dtypes or using mixed of lower and higher dtypes numbers increases the performance of the processing numbers.

In [ ]:
B = tf.constant([1, 2, 3], dtype = tf.float32)
B.dtype

tf.float32

In [ ]:
D = tf.cast(B, dtype = tf.float16)
D.dtype

tf.float16

In [ ]:
B.dtype

tf.float32